blank_issues_enabled: true
contact_links:
  - name: ğŸ†• Create new issue
    url: http://new-issue.go-admin.dev
    about: The issue which is not created via http://new-issue.go-admin.dev will be closed immediately.
  - name: ğŸ†• åˆ›å»ºä¸€ä¸ªæ–° Issue
    url: http://new-issue.go-admin.dev
    about: ä¸æ˜¯ç”¨ http://new-issue.go-admin.dev åˆ›å»ºçš„ issue ä¼šè¢«æœºå™¨äººè‡ªåŠ¨å…³é—­ã€‚
